# Generated by Django 4.0.4 on 2022-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasales',
            name='jenis_kelamin',
            field=models.CharField(choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], default='laki-laki', max_length=10),
        ),
    ]
