# Generated by Django 4.0.4 on 2022-05-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_datasales_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatoko',
            name='Jenis_toko',
            field=models.CharField(choices=[('P&D', 'P&D'), ('WARUNG RE/NOO', 'WARUNG RE/NOO'), ('MTI RE/NOO', 'MTI RE/NOO')], default='P&D', max_length=13),
        ),
    ]
