# Generated by Django 4.0.4 on 2022-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_datatoko_jenis_toko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatoko',
            name='kabupaten_kota',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datatoko',
            name='kecamatan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datatoko',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datatoko',
            name='longtitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datatoko',
            name='provinsi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datatoko',
            name='village',
            field=models.CharField(max_length=50),
        ),
    ]
