# Generated by Django 4.0.4 on 2022-05-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_datatoko_kabupaten_kota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataroti',
            old_name='harga_roti',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='dataroti',
            old_name='kode_roti',
            new_name='kode',
        ),
        migrations.RenameField(
            model_name='dataroti',
            old_name='nama_roti',
            new_name='nama',
        ),
    ]
